# Who we are
COMPONENTNAME:=test

# Where's the top
BASEDIR:=../..

# What we need from outside
INCLUDES += -I $(BASEDIR)/src/core/include -I $(BASEDIR)/src/elements/include -I $(BASEDIR)/src/gui/include -I $(BASEDIR)/src/sim/include

# Do the library thing
include $(BASEDIR)/config/Makelib.mk
