# Who we are
COMPONENTNAME:=platform-tile

# Where's the top
BASEDIR:=../..

# What we need from outside
override INCLUDES +=

# Special dispensation for IsLocalPlatformSpecific..
CPPFLAGS += -Wno-return-local-addr

# Do the library thing
include $(BASEDIR)/config/Makelib.mk
