# Who we are
COMPONENTNAME:=sim

# Where's the top
BASEDIR:=../..

# What we need from outside
INCLUDES += -I $(BASEDIR)/src/core/include -I $(BASEDIR)/src/elements/include

# Do the library thing
include $(BASEDIR)/config/Makelib.mk
